# Acá va el nombre (Integracion Continua)
name: CI

# Acá se declaran los eventos
on:

# Si se ejecuta el push cada vez
 push:
 workflow_dispatch:

# Acá es donde se declaran los trabajos y los pasos (jobs --< steps)
jobs:
  
 build:   
  runs-on: ubuntu-latest  
  steps:  
   - uses: actions/checkout@v3   
   - name: Run a multi-line script
     run: |
       echo "Hola mundo!"

 test:
  runs-on: ubuntu-latest
  needs: build
  steps:
   - name: test
     run: |
      echo "Hello word!"
